### ISSUE TITLE
One Time Password Remains Valid After The Term Of Validity

### ISSUE THREAD

**Issue by jhezjkp** [parkghost/TOTP-authentication-demo#1]
On the demo(http://totp-authentication-demo.herokuapp.com/) you provided，I created one account and bind totp to my 1password， and valid for the first time with 903992,  wait for the totp changed and try another validation with 903992, show validation passed. And then i tried again with the newly generated totp password, which turns to be another validation pass.

If  one of the totp password leaked, then it becames unsafe....

**Comment by jhezjkp** [comment]
I read your blog about this repo, learned that it will be valid in 90s because of the datetime deviation between server and client, so I made another test.
1. validate with totp1 at time 0: passed
2. validate with totp1 at time 50s: passed
3. validate with totp1 at time 1m90s: still passed
4. validate with totp1 at time 3m57: still passed
5. validate with totp1 at time 11m: failed

**Comment by parkghost** [comment]
Oops, I forget to change the `WINDOW` value after debugging, the value should be 3. fix https://github.com/parkghost/TOTP-authentication-demo/commit/ddb6dee73652aee750ceae57c6c1f73897f5eefd

This change will be deployed to the demo site within a few days

Thanks for the information you provided.
